FROM node:20 AS builder

WORKDIR /src

COPY . .

RUN yarn --pure-lockfile install --ignore-engines
ENV RANCHER_ENV=harvester
ENV API=https://192.168.100.10
RUN yarn build

EXPOSE 80
EXPOSE 443
ENTRYPOINT ["yarn"]
CMD ["start"]